title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue with Metamorph!
  - type: input
    id: version
    attributes:
      label: Metamorph Version
      description: Which version of Metamorph are you using?
      placeholder: e.g. 2.0.9
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I run 'metamorph ui', it...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Terminal Logs / Event Logs
      description: Please paste any relevant logs from the terminal or the LIVE SWARM event log.
      render: shell
